CREATE TABLE CARGO (
CdCargo varchar2(2) not null,
NmCargo varchar2(40) null,
VrSalario NUMERIC(8,2)
);

ALTER TABLE cargo
ADD CONSTRAINT PK_CARGO PRIMARY KEY (CdCargo);

CREATE TABLE DEPTO (
CDDEPTO VARCHAR2(2) NOT NULL,
NMDEPTO VARCHAR2(40),
RAMAL NUMBER(8,0)
);

ALTER TABLE DEPTO
ADD CONSTRAINT PK_DEPTO PRIMARY KEY (CDDEPTO);

CREATE TABLE FUNCIONARIO(
NRMATRIC NUMBER(8,0) NOT NULL,
NMFUNC VARCHAR(80),
DTADM DATE,
SEXO CHAR,
CdCargo varchar2(2) not null,
CDDEPTO VARCHAR2(2) NOT NULL
);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (NRMATRIC);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_DEPTO
   FOREIGN KEY (CDDEPTO)
   REFERENCES DEPTO (CDDEPTO);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_CARGO
   FOREIGN KEY (CDCARGO)
   REFERENCES CARGO (CDCARGO);
   
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('F','M'));

SELECT * FROM all_tables;

INSERT ALL
  INTO CARGO (CdCargo, NmCargo, VrSalario) VALUES ('C1', 'COZINHEIRA', 350)
  INTO CARGO (CdCargo, NmCargo, VrSalario) VALUES ('C3', 'AUX.ESCRITORIO', 450)
  INTO CARGO (CdCargo, NmCargo, VrSalario) VALUES ('C7', 'VIGIA', 400)
  INTO CARGO (CdCargo, NmCargo, VrSalario) VALUES ('C2', 'MECANICO', 750)
  INTO CARGO (CdCargo, NmCargo, VrSalario) VALUES ('C5', 'GERENTE', 2300)
  INTO CARGO (CdCargo, NmCargo, VrSalario) VALUES ('C4', 'ESCRITURADO', 600)
SELECT * FROM dual;

INSERT ALL
  INTO DEPTO (CdDepto, NmDepto, Ramal) VALUES ('D1', 'ADMINISTRACAO', 221)
  INTO DEPTO (CdDepto, NmDepto, Ramal) VALUES ('D2', 'OFICINA', 235)
  INTO DEPTO (CdDepto, NmDepto, Ramal) VALUES ('D3', 'SERVICOS GERAIS', 243)
  INTO DEPTO (CdDepto, NmDepto, Ramal) VALUES ('D4', 'VENDAS', 258)
SELECT * FROM dual;

INSERT ALL
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1001, 'JOAO SAMPAIO', TO_DATE('10/08/93', 'dd/mm/yy'), 'M', 'C2', 'D2')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1041, 'LUCIO TORRES', TO_DATE('02/03/94', 'dd/mm/yy'), 'M', 'C2', 'D2')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1034, 'ROBERTO PEREIRA', TO_DATE('23/05/92', 'dd/mm/yy'), 'M', 'C3', 'D1')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1021, 'JOSE NOGUEIRA', TO_DATE('10/11/94', 'dd/mm/yy'), 'M', 'C3', 'D1')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1029, 'RUTH DE SOUZA', TO_DATE('05/01/92', 'dd/mm/yy'), 'F', 'C1', 'D3')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1095, 'MARIA DA SILVA', TO_DATE('03/09/92', 'dd/mm/yy'), 'F', 'C4', 'D1')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1023, 'LUIZ DE ALMEIDA', TO_DATE('12/01/93', 'dd/mm/yy'), 'M', 'C2', 'D2')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1042, 'PEDRO PINHEIRO', TO_DATE('29/07/94', 'dd/mm/yy'), 'M', 'C4', 'D1')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1048, 'ANA SILVEIRA', TO_DATE('01/06/93', 'dd/mm/yy'), 'F', 'C5', 'D1')
  INTO FUNCIONARIO (NrMatric, NmFunc, DtAdm, Sexo, CdCargo, CdDepto) VALUES (1015, 'PAULO RODRIGUES', TO_DATE('17/08/92', 'dd/mm/yy'), 'M', 'C2', 'D2')
SELECT * FROM dual;

UPDATE FUNCIONARIO 
SET CDCARGO = 'C5'
WHERE NRMATRIC = 1021;

UPDATE FUNCIONARIO 
SET CDCARGO = 'C1'
WHERE NRMATRIC = 1021 OR
NRMATRIC = 1042;

DELETE FROM CARG WHERE CDCARGO = 'C4';

/*-------------------------------------------------------------------------------------*/

ALTER TABLE FUNCIONARIO
ADD nrfilhos NUMBER(2,0);

UPDATE FUNCIONARIO 
SET NRFILHOS = 0
WHERE NRMATRIC >= 1001 AND
NRMATRIC <= 1004;

UPDATE FUNCIONARIO 
SET NRFILHOS = 2
WHERE NRMATRIC >= 1015 AND
NRMATRIC <= 1029;

UPDATE FUNCIONARIO 
SET NRFILHOS = 3
WHERE NRMATRIC >= 1034 AND
NRMATRIC <= 1042;

UPDATE FUNCIONARIO 
SET NRFILHOS = 4
WHERE NRMATRIC >= 1048 AND
NRMATRIC <= 1095;

SELECT NRMATRIC as "Matricula", NMFUNC as "Nome", DTADM as "Data de admissão",
EXTRACT(YEAR FROM DTADM) AS "Qnt anos" FROM
FUNCIONARIO;

SELECT CDCARGO, NMCARGO, VRSALARIO, VRSALARIO - (VRSALARIO*0.075) as "Reduzido 7%" FROM CARGO;

SELECT * FROM CARGO WHERE CDCARGO = 'C3';

SELECT * FROM CARGO WHERE VRSALARIO >= 1700;

SELECT * FROM CARGO WHERE VRSALARIO > 400 AND VRSALARIO < 1200;

SELECT * FROM CARGO 
WHERE NMCARGO LIKE '%MECANICO%'
OR
NMCARGO LIKE '%COZINHEIRA%';

SELECT * FROM CARGO 
WHERE NMCARGO NOT LIKE '%MECANICO%'
OR
NMCARGO NOT LIKE '%COZINHEIRA%';

SELECT * FROM FUNCIONARIO WHERE NRFILHOS IN (2, 4);

SELECT * FROM FUNCIONARIO WHERE NRFILHOS IN (2, 4)
AND DTADM < to_date('01-JAN-90','DD-MON-YY');

SELECT * FROM FUNCIONARIO WHERE NRFILHOS < 2 OR NRFILHOS > 3;

SELECT * FROM FUNCIONARIO WHERE (NRFILHOS < 2 OR NRFILHOS > 3) AND NRFILHOS > 0;

SELECT * FROM FUNCIONARIO WHERE (NRFILHOS < 2 OR NRFILHOS > 3) 
AND NRFILHOS NOT IN (0);

SELECT * FROM FUNCIONARIO WHERE NRFILHOS IN (2, 3);

SELECT * FROM FUNCIONARIO WHERE NMFUNC LIKE '%SILVA%';

SELECT * FROM FUNCIONARIO WHERE NMFUNC LIKE 'R%';

SELECT NMFUNC FROM FUNCIONARIO WHERE NMFUNC LIKE '%SANTOS%';

SELECT NRMATRIC, NMFUNC, CDDEPTO FROM FUNCIONARIO
WHERE NRMATRIC IN (1001, 1004, 1095);

SELECT F.NMFUNC, F.CDDEPTO FROM FUNCIONARIO F, DEPTO D 
WHERE D.CDDEPTO != 'D2' AND F.CDDEPTO = D.CDDEPTO;

SELECT * FROM FUNCIONARIO WHERE NMFUNC LIKE '%SILVA%';

SELECT * FROM CARGO WHERE VRSALARIO != 2000;

